version: "3.9"  # optional since v1.27.0
services:
  filmantix-api:
    image: ghcr.io/mathieugery/filmantix/filmantix-api:latest
    container_name: filmantix-api
    restart: always
    volumes:
      - ${PWD}/api/config/config.yaml:/app/config/config.yaml
    ports:
      - 8888:8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filmantix-api-http.entrypoints=http"
      - "traefik.http.routers.filmantix-api-http.rule=Host(`filmantix-api.gery.me`)"
      - "traefik.http.routers.filmantix-api-http.middlewares=filmantix-api-https@docker"
      - "traefik.http.middlewares.filmantix-api-https.redirectscheme.scheme=https"
      - "traefik.http.routers.filmantix-api.rule=Host(`filmantix-api.gery.me`)"
      - "traefik.http.routers.filmantix-api.entrypoints=https"
      - "traefik.http.routers.filmantix-api.tls.certresolver=gery"
      - "traefik.http.services.filmantix-api.loadbalancer.server.port=443"
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dfgdfg
      APP_DB_USER: filmantix
      APP_DB_PASS: dfgdfg
      APP_DB_NAME: filmantix
    ports:
      - 5432:5432

networks:
  web:
    external: true